# Generated by Django 2.2 on 2020-09-26 06:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200926_0329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ShippingAddress',
            new_name='Shipping_Address',
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='expiration',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('(0[1-9]|10|11|12)/[0-9]{2}$')]),
        ),
    ]
